#include "edyn/serialization/comp/aabb_s11n.hpp"
#include "edyn/serialization/comp/angvel_s11n.hpp"
#include "edyn/serialization/comp/linvel_s11n.hpp"
#include "edyn/serialization/comp/orientation_s11n.hpp"
#include "edyn/serialization/comp/position_s11n.hpp"
#include "edyn/serialization/comp/collision_filter_s11n.hpp"
#include "edyn/serialization/comp/constraint_s11n.hpp"