#include "edyn/serialization/math_s11n.hpp"
#include "edyn/serialization/std_s11n.hpp"
#include "edyn/serialization/static_tree_s11n.hpp"
#include "edyn/serialization/triangle_mesh_s11n.hpp"
#include "edyn/serialization/paged_triangle_mesh_s11n.hpp"
#include "edyn/serialization/entt_s11n.hpp"
#include "edyn/serialization/file_archive.hpp"
#include "edyn/serialization/memory_archive.hpp"