#ifndef EDYN_NETWORKING_SETTINGS_SERVER_NETWORK_SETTINGS_HPP
#define EDYN_NETWORKING_SETTINGS_SERVER_NETWORK_SETTINGS_HPP

namespace edyn {

struct server_network_settings {

};

}

#endif // EDYN_NETWORKING_SETTINGS_SERVER_NETWORK_SETTINGS_HPP
