#ifndef EDYN_NETWORKING_SETTINGS_SERVER_NETWORKING_SETTINGS_HPP
#define EDYN_NETWORKING_SETTINGS_SERVER_NETWORKING_SETTINGS_HPP

namespace edyn {

struct server_networking_settings {

};

}

#endif // EDYN_NETWORKING_SETTINGS_SERVER_NETWORKING_SETTINGS_HPP
